In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
hub_nash=pd.read_csv('../data/hub_requests.csv')

/Users/nicolemuldowney/opt/anaconda3/envs/geo/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (17) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [29]:
res_survey = pd.read_csv('../data/metro_resident_survey.csv')
#Metro Resident Survey data from: https://data.nashville.gov/General-Government/Metro-Resident-Survey-Responses/nux7-cwab/data

In [30]:
res_survey.head()

,Period,Start Date,End Date,ZIP Code,Service District,Quality of Life,Overall Feeling of Safety,Neighborhood Safety,City Appearance,Neighborhood Appearance,...,Race / Ethnicity - Black,Race / Ethnicity - Hispanic,Race / Ethnicity - Asian or Pacific Islander,Race / Ethnicity - Native American or Alaskan Native,Race / Ethnicity - Other,Race / Ethnicity - Other Definition,Total Annual Household Income,Age,Gender Identity,Education Attained
0,2018Q2,06/21/2018,07/16/2018,37208,Urban Services District,Neutral,Neutral,Neutral,Neutral,Satisfied,...,Yes,NaN,NaN,NaN,NaN,NaN,NaN,25-34,Female,High school graduate
1,2018Q2,06/21/2018,07/16/2018,37211,Urban Services District,Satisfied,Satisfied,Satisfied,Neutral,Satisfied,...,NaN,NaN,NaN,NaN,NaN,NaN,"$100,000 or more",45-54,Female,Graduate degree
2,2018Q2,06/21/2018,07/16/2018,37208,Urban Services District,Very Satisfied,Neutral,Satisfied,Satisfied,Satisfied,...,NaN,NaN,NaN,NaN,NaN,NaN,"$30,000 to $59,999",25-34,Male,Bachelor's degree
3,2018Q2,06/21/2018,07/16/2018,37203,Urban Services District,Satisfied,Very Satisfied,Satisfied,Satisfied,Satisfied,...,NaN,NaN,NaN,NaN,NaN,NaN,"$30,000 to $59,999",25-34,Male,Bachelor's degree
4,2018Q1,02/01/2018,03/06/2018,37138,General Services District,Satisfied,Satisfied,Satisfied,NaN,Satisfied,...,NaN,NaN,NaN,NaN,NaN,NaN,"$60,000 to $99,999",45-54,Female,NaN

In [31]:
res_survey.columns

Index(['Period', 'Start Date', 'End Date', 'ZIP Code', 'Service District',
       'Quality of Life', 'Overall Feeling of Safety', 'Neighborhood Safety',
       'City Appearance', 'Neighborhood Appearance',
       ...
       'Race / Ethnicity - Black', 'Race / Ethnicity - Hispanic',
       'Race / Ethnicity - Asian or Pacific Islander',
       'Race / Ethnicity - Native American or Alaskan Native',
       'Race / Ethnicity - Other', 'Race / Ethnicity - Other Definition',
       'Total Annual Household Income', 'Age', 'Gender Identity',
       'Education Attained'],
      dtype='object', length=181)

In [82]:
#drop some columns to clean data/ focus on what columns are needed for analysis
res_survey=res_survey.drop(columns= ['Race / Ethnicity -- Asian or Pacific Islander'])

KeyError: "['Race / Ethnicity -- Asian or Pacific Islander'] not found in axis"

In [67]:
res_survey['Quality of Life'].unique()

array(['Neutral', 'Satisfied', 'Very Satisfied', 'Very Dissatisfied',
       'Dissatisfied', "Don't Know"], dtype=object)

In [65]:
high_quality = res_survey.loc[(res_survey['Quality of Life'] == 'Very Satisfied')]
high_quality

,Start Date,End Date,ZIP Code,Service District,Quality of Life,Overall Feeling of Safety,Neighborhood Safety,City Appearance,Neighborhood Appearance,Nashville as Residence,...,Other School Attendance,Other School Definition,School Quality,Own or Rent,Years Lived in Davidson County,Business Owner / Operator,Race / Ethnicity - White,Total Annual Household Income,Age,Education Attained
2,06/21/2018,07/16/2018,37208,Urban Services District,Very Satisfied,Neutral,Satisfied,Satisfied,Satisfied,Excellent,...,NaN,NaN,NaN,Own,10.0,No,Yes,"$30,000 to $59,999",25-34,Bachelor's degree
5,06/21/2018,07/16/2018,37207,Urban Services District,Very Satisfied,Very Satisfied,Very Satisfied,Very Satisfied,Very Satisfied,Excellent,...,NaN,NaN,NaN,Own,17.0,No,Yes,"$100,000 or more",35-44,Bachelor's degree
11,06/21/2018,07/16/2018,37211,Urban Services District,Very Satisfied,Neutral,Very Satisfied,Very Satisfied,Very Satisfied,Excellent,...,NaN,NaN,Average,Own,27.0,No,Yes,"$30,000 to $59,999",35-44,High school graduate
12,06/21/2018,07/16/2018,37207,Urban Services District,Very Satisfied,Satisfied,Dissatisfied,Satisfied,Dissatisfied,Excellent,...,NaN,NaN,NaN,Own,5.0,No,Yes,"$100,000 or more",25-34,Bachelor's degree
13,06/21/2018,07/16/2018,37204,Urban Services District,Very Satisfied,Satisfied,Satisfied,Neutral,Dissatisfied,Excellent,...,NaN,NaN,NaN,Own,3.0,No,Yes,"$100,000 or more",35-44,Graduate degree
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2141,02/13/2019,03/22/2019,37218,Urban Services District,Very Satisfied,Dissatisfied,Satisfied,Satisfied,Neutral,Good,...,NaN,NaN,NaN,Rent,60.0,No,NaN,"Under $30,000",45-54,High school graduate
2143,02/13/2019,03/22/2019,37207,Urban Services District,Very Satisfied,Very Satisfied,Dissatisfied,Satisfied,Dissatisfied,Excellent,...,NaN,NaN,NaN,Own,64.0,No,NaN,"$30,000 to $59,999",45-54,Bachelor's degree
2145,02/13/2019,03/22/2019,37115,General Services District,Very Satisfied,Very Satisfied,Satisfied,Satisfied,Neutral,Excellent,...,NaN,NaN,NaN,Own,40.0,No,Yes,"$60,000 to $99,999",25-34,Graduate degree
2149,02/13/2019,03/22/2019,37205,Urban Services District,Very Satisfied,Satisfied,Very Satisfied,Very Satisfied,Very Satisfied,Excellent,...,NaN,NaN,NaN,Own,42.0,Yes,Yes,"$100,000 or more",55-64,Graduate degree
2150,02/13/2019,03/22/2019,37215,Urban Services District,Very Satisfied,Satisfied,Satisfied,Satisfied,Satisfied,Good,...,NaN,NaN,Excellent,Own,10.0,No,Yes,"$100,000 or more",25-34,Graduate degree